### A build trigger set up in the Google lage-genoppi project will
### initiate Cloud Build using this file upon a push to master branch

steps:

# (1) Build the shiny app container image (using Dockerfile)
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/genoppi:$COMMIT_SHA', '.']

# (2) Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/genoppi:$COMMIT_SHA']

# (3) Deploy container image to Cloud Run
# (deployed URL linked to lagelab.org/genoppi)
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'genoppi'
  - '--image'
  - 'gcr.io/$PROJECT_ID/genoppi:$COMMIT_SHA'
  - '--region'
  - 'us-east4'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--max-instances'
  - '200'
  - '--memory'
  - '2048Mi'

images:
- 'gcr.io/$PROJECT_ID/genoppi:$COMMIT_SHA'
timeout: 3600s
